version: "3.9"
services:
  db:
    image: postgres:15.1-alpine
    container_name: db
    restart: always
    ports:
      - "2345:5432"
    volumes:
      - ../DB/smallData/.:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    container_name: autodrome-app
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL=${SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL}
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE=${SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE}
      - JWT_SECRET=${JWT_SECRET}
      - GRAPHHOPPER_API_KEY=${GRAPHHOPPER_API_KEY}
      - CLIENT_ZONE_ID=${CLIENT_ZONE_ID}
      - TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
