-- we don't know how to generate root <with-no-name> (class Root) :(
create sequence users_id_seq;

alter sequence users_id_seq owner to postgres;

create table vehicle_brands
(
    id               bigint generated by default as identity
        primary key,
    name             varchar          not null,
    type             varchar          not null,
    tank             double precision not null,
    load_capacity    double precision not null,
    number_of_places integer          not null
);

alter table vehicle_brands
    owner to postgres;

create table enterprise
(
    id        bigint generated by default as identity
        primary key,
    name      varchar not null,
    city      varchar not null,
    founded   date    not null,
    time_zone varchar(255) default 'UTC'::character varying
);

alter table enterprise
    owner to postgres;

create table vehicle
(
    id                 bigint generated by default as identity
        primary key,
    number             varchar not null,
    cost               integer not null,
    year_of_production integer not null,
    mileage            integer not null,
    brand_id           bigint
        references vehicle_brands,
    enterprise_id      bigint
        references enterprise,
    buy_date_time_utc  timestamp default now()
);

alter table vehicle
    owner to postgres;

create table driver
(
    id            bigint generated by default as identity
        primary key,
    name          varchar not null,
    salary        integer not null,
    is_active     boolean default false,
    enterprise_id bigint
        references enterprise,
    vehicle_id    bigint
        references vehicle
);

alter table driver
    owner to postgres;

create table person
(
    id       bigint generated by default as identity
        constraint users_pkey
            primary key,
    username varchar(255) not null
        constraint users_username_key
            unique,
    password varchar(255) not null,
    role     varchar(255) default 'ROLE_USER'::character varying
);

alter table person
    owner to postgres;

alter sequence users_id_seq owned by person.id;

create table manager
(
    id bigint not null
        primary key
        constraint manager_person_id_fk
            references person
);

alter table manager
    owner to postgres;

create table enterprise_manager
(
    manager_id    bigint not null
        references manager,
    enterprise_id bigint not null
        references enterprise,
    primary key (manager_id, enterprise_id)
);

alter table enterprise_manager
    owner to postgres;

create table gps_point
(
    id         bigint generated by default as identity
        primary key,
    vehicle_id bigint                   not null
        references vehicle,
    date_time  timestamp with time zone not null,
    x          double precision         not null,
    y          double precision         not null
);

alter table gps_point
    owner to postgres;

create index gps_point_vehicle_id_idx
    on gps_point (vehicle_id);

create table trip
(
    id             bigint generated by default as identity
        primary key,
    vehicle_id     bigint                   not null
        references vehicle,
    start_time_utc timestamp with time zone not null
        unique,
    end_time_utc   timestamp with time zone not null
        unique,
    length_km      integer default 0        not null
);

alter table trip
    owner to postgres;

